coverage:
  status:
    project:
      default:
        target: 78%
        threshold: 1%
    patch:
      default:
        enabled: false

  ignore:
    - '**/entities/**'
    - '**/di/**'
    - '**/theme/**'
    - '**/core/services/i_geo_locator_wrapper.dart'

