coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        enabled: false

  ignore:
    - '**/entities/**'
    - '**/di/**'
    - '**/theme/**'

