name: Flutter CI

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - excelFeature

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Create .env file
        run: |
          echo "EXCEL_BASE_URL=https://example.com" >> .env
          echo "EXCEL_URL=/spreadsheet.xlsx" >> .env
          echo "EXCEL_FORMAT=xlsx" >> .env
          echo "FIREBASE_API_KEY_ANDROID=dummy" >> .env
          echo "FIREBASE_APP_ID_ANDROID=dummy" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=123" >> .env
          echo "FIREBASE_PROJECT_ID=dummy" >> .env
          echo "FIREBASE_STORAGE_BUCKET=dummy" >> .env
          echo "FIREBASE_API_KEY_IOS=dummy" >> .env
          echo "FIREBASE_APP_ID_IOS=dummy" >> .env
          echo "FIREBASE_IOS_BUNDLE_ID=dummy" >> .env

      - name: Create google-services.json
        run: |
          mkdir -p android/app
          echo '{
            "project_info": {
              "project_number": "${{ secrets.PROJECT_NUMBER }}",
              "project_id": "${{ secrets.PROJECT_ID }}",
              "storage_bucket": "${{ secrets.STORAGE_BUCKET }}"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "${{ secrets.MOBILESDK_APP_ID }}",
                  "android_client_info": {
                    "package_name": "com.example.vegawallet"
                  }
                },
                "oauth_client": [
                  {
                    "client_id": "${{ secrets.OAUTH_CLIENT_ID_1 }}",
                    "client_type": 1,
                    "android_info": {
                      "package_name": "com.example.vegawallet",
                      "certificate_hash": "${{ secrets.CERTIFICATE_HASH_1 }}"
                    }
                  },
                  {
                    "client_id": "${{ secrets.OAUTH_CLIENT_ID_2 }}",
                    "client_type": 1,
                    "android_info": {
                      "package_name": "com.example.vegawallet",
                      "certificate_hash": "${{ secrets.CERTIFICATE_HASH_2 }}"
                    }
                  },
                  {
                    "client_id": "${{ secrets.OAUTH_CLIENT_ID_3 }}",
                    "client_type": 3
                  }
                ],
                "api_key": [
                  {
                    "current_key": "${{ secrets.API_KEY }}"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": [
                      {
                        "client_id": "${{ secrets.OAUTH_CLIENT_ID_3 }}",
                        "client_type": 3
                      },
                      {
                        "client_id": "${{ secrets.OAUTH_CLIENT_ID_4 }}",
                        "client_type": 2,
                        "ios_info": {
                          "bundle_id": "vegawallet"
                        }
                      }
                    ]
                  }
                }
              }
            ],
            "configuration_version": "1"
          }' > android/app/google-services.json
      

      - name: Create GoogleService-Info.plist
        run: |
          mkdir -p ios/Runner
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CLIENT_ID</key>
            <string>dummy-client-id.apps.googleusercontent.com</string>
            <key>REVERSED_CLIENT_ID</key>
            <string>com.googleusercontent.apps.dummy-client-id</string>
            <key>ANDROID_CLIENT_ID</key>
            <string>dummy-android-client-id.apps.googleusercontent.com</string>
            <key>API_KEY</key>
            <string>dummy-api-key</string>
            <key>GCM_SENDER_ID</key>
            <string>123456789012</string>
            <key>PLIST_VERSION</key>
            <string>1</string>
            <key>BUNDLE_ID</key>
            <string>com.example.vegawallet</string>
            <key>PROJECT_ID</key>
            <string>vega-wallet</string>
            <key>STORAGE_BUCKET</key>
            <string>vega-wallet.appspot.com</string>
            <key>IS_ADS_ENABLED</key>
            <false/>
            <key>IS_ANALYTICS_ENABLED</key>
            <false/>
            <key>IS_APPINVITE_ENABLED</key>
            <true/>
            <key>IS_GCM_ENABLED</key>
            <true/>
            <key>IS_SIGNIN_ENABLED</key>
            <true/>
            <key>GOOGLE_APP_ID</key>
            <string>1:1098052959751:ios:dummy-app-id</string>
          </dict>
          </plist>' > ios/Runner/GoogleService-Info.plist

      - name: Install dependencies
        run: flutter pub get

      - name: Run build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze code
        run: flutter analyze

      - name: Build Android project
        run: flutter build apk --release

      - name: Build iOS project
        run: flutter build ios --no-codesign

      - name: Run tests
        run: flutter test --coverage

      - name: Upload Android build to Firebase App Distribution
        uses: nickwph/firebase-app-distribution-action@v1
        with:
          app: ${{secrets.APP_ID}}
          credentials: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          file: build/app/outputs/flutter-apk/app-release.apk
          groups: "testers"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
