name: Flutter CI

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - excelFeature

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Specify the Flutter version

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Create .env file
        run: |
          echo "EXCEL_BASE_URL=https://example.com" >> .env
          echo "EXCEL_URL=/spreadsheet.xlsx" >> .env
          echo "EXCEL_FORMAT=xlsx" >> .env
          echo "FIREBASE_API_KEY_ANDROID=kekeke" >> .env
          echo "FIREBASE_APP_ID_ANDROID=kekeke" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=123" >> .env
          echo "FIREBASE_PROJECT_ID=keke" >> .env
          echo "FIREBASE_STORAGE_BUCKET=keke" >> .env
          echo "FIREBASE_API_KEY_IOS=kekeke" >> .env
          echo "FIREBASE_APP_ID_IOS=keke" >> .env
          echo "FIREBASE_IOS_BUNDLE_ID=keke" >> .env

      - name: Create google-services.json
        run: |
          mkdir -p android/app
          echo '{
            "project_info": {
              "project_number": "1234",
              "project_id": "vega-wallet",
              "storage_bucket": "vega-wallet.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1111",
                  "android_client_info": {
                    "package_name": "com.example.vegawallet"
                  }
                },
                "oauth_client": [
                  {
                    "client_id": "1111",
                    "client_type": 1,
                    "android_info": {
                      "package_name": "com.example.vegawallet",
                      "certificate_hash": "1111"
                    }
                  },
                  {
                    "client_id": "1111",
                    "client_type": 3
                  }
                ],
                "api_key": [
                  {
                    "current_key": "123"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": [
                      {
                        "client_id": "1111",
                        "client_type": 3
                      },
                      {
                        "client_id": "1111",
                        "client_type": 2,
                        "ios_info": {
                          "bundle_id": "com.example.vegawallet"
                        }
                      }
                    ]
                  }
                }
              }
            ],
            "configuration_version": "1"
          }' > android/app/google-services.json

      - name: Create GoogleService-Info.plist
        run: |
          mkdir -p ios/Runner
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CLIENT_ID</key>
            <string>123456789012-abcdefg123456.apps.googleusercontent.com</string>
            <key>REVERSED_CLIENT_ID</key>
            <string>com.googleusercontent.apps.123456789012-abcdefg123456</string>
            <key>API_KEY</key>
            <string>kekeke</string>
            <key>GCM_SENDER_ID</key>
            <string>123456789012</string>
            <key>PLIST_VERSION</key>
            <string>1</string>
            <key>BUNDLE_ID</key>
            <string>com.example</string>
            <key>PROJECT_ID</key>
            <string>example</string>
            <key>STORAGE_BUCKET</key>
            <string>example.appspot.com</string>
            <key>IS_ADS_ENABLED</key>
            <false/>
            <key>IS_ANALYTICS_ENABLED</key>
            <true/>
            <key>IS_APPINVITE_ENABLED</key>
            <true/>
            <key>IS_GCM_ENABLED</key>
            <true/>
            <key>IS_SIGNIN_ENABLED</key>
            <true/>
            <key>GOOGLE_APP_ID</key>
            <string>1:123456789012:ios:abc123def456</string>
            <key>DATABASE_URL</key>
            <string>https://example.firebaseio.com</string>
          </dict>
          </plist>' > ios/Runner/GoogleService-Info.plist

      - name: Install dependencies
        run: flutter pub get

      - name: Update Podfile with Deployment Target
        run: sed -i '' 's/platform :ios, .*/platform :ios, '12.0'/g' ios/Podfile

      - name: Add GoogleService-Info.plist to Xcode project
        run: |
          ruby -e "require 'xcodeproj'; project = Xcodeproj::Project.open('ios/Runner.xcodeproj'); file_ref = project.new_file('ios/Runner/GoogleService-Info.plist'); main_group = project.main_group.find_subpath(File.join('Runner'), true); main_group.new_reference(file_ref); project.save"

      - name: Run build runner
        run: flutter pub run build_runner build

      - name: Analyze code
        run: flutter analyze

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build Android project
        run: flutter build apk --debug # Use `flutter build apk` for release build

      - name: Build iOS project
        run: flutter build ios --no-codesign

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
