name: Flutter CI

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - excelFeature

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Specify the Flutter version

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Create .env file
        run: |
          echo "EXCEL_BASE_URL=https://example.com" >> .env
          echo "EXCEL_URL=/spreadsheet.xlsx" >> .env
          echo "EXCEL_FORMAT=xlsx" >> .env

      - name: Copy firebase_options.dart
        run: lib/firebase_options.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Run build runner
        run: flutter pub run build_runner build

      - name: Analyze code
        run: flutter analyze

      - name: Build Android project
        run: flutter build apk --debug # Use `flutter build apk` for release build

      - name: Build iOS project
        run: flutter build ios --no-codesign

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
